### ISSUE TITLE
Static Site Generator

### ISSUE THREAD

**Issue by FabianAhammer** [htblaleonie/htblaleonie.github.io#3]
Generate the Leonie landing page from File/etc

**Comment by stefnotch** [comment]
Regarding an AsciiDoc documentation, here are some links to check out:

> https://opensource.com/article/17/8/asciidoc-web-development
> 
> Dieses Buch ist vollständig in AsciiDoc geschrieben:
> https://github.com/clojure-cookbook/clojure-cookbook
> 
> https://neo4j.com/docs/operations-manual/current/ bzw https://neo4j.com/docs/
> https://git-scm.com/docs/user-manual  --> https://github.com/git/git-scm.com/blob/master/ARCHITECTURE.md
> https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html
> Openshift https://github.com/openshift/openshift-docs
> http://enterprisewebbook.com/
> https://golo-lang.org/documentation/next/
> https://www.jfrog.com/confluence/display/BT/Bintray+REST+API
> https://spring.io/projects/spring-boot -> https://github.com/spring-projects/spring-boot
> SEHR INTERESSANT -> https://spring.io/blog/2013/12/13/spring-s-getting-started-guides-migrated-to-asciidoctor
> https://infinispan.org/docs/7.0.x/user_guide/user_guide.html
> http://docs.groovy-lang.org/latest/html/documentation/
> https://www.hivemq.com/docs/hivemq/4.3/user-guide/introduction.html
> https://docs.jboss.org/hibernate/orm/6.0/quickstart/html_single/
> 
> Man kann AsciiDoc für SiteGenerator verwenden
> zB https://jbake.org/docs/2.6.4/
> 
> https://www.activiti.org/userguide/
> https://projectreactor.io/docs/core/release/reference/
> https://github.com/JavaMoney/jsr354-api/blob/master/src/main/asciidoc/JavaMoneySpecification.adoc
> http://yfain.github.io/Java4Kids/
> https://docs.fedoraproject.org/en-US/docs/
> https://gradle.org/guides/
> 
> 
> https://itsfoss.com/asciidoc-guide/
> https://www.wappalyzer.com/technologies/asciidoc
> https://antora.org/ The multi-repository documentation site generator for tech writers who writing in AsciiDoc.
> https://github.com/asciidoctor/asciidoctor.org/issues/270
> -- Prof. Stuetz

Apparently AsciiDoc is rather popular in the Java ecosystem.

**Comment by stefnotch** [comment]
https://github.com/hakimel/reveal.js/pull/2609

**Comment by stefnotch** [comment]
https://docusaurus.io/en/users
https://github.com/facebook/docusaurus/issues/1258#issuecomment-569940159

**Comment by stefnotch** [comment]
Hmm, docusaurus uses React. 
We could use VuePress and use the following Mermaid plugin
https://www.npmjs.com/package/vuepress-plugin-mermaidjs

**Comment by stefnotch** [comment]
**VuePress Themes**
- https://github.com/FriendlyUser/vuepress-theme-cool
- https://github.com/lisniuse/vuepress-theme-thindark
- https://github.com/Molunerfinn/vuepress-theme-melody
- https://github.com/arab-open-source/vuepress-theme-vuetify
- https://github.com/tolking/vuepress-theme-ououe
- https://github.com/cnguu/vuepress-theme-yur
- https://github.com/z3by/vuepress-theme-modern-blog
- https://github.com/jsmith/vuepress-theme-terminal
- https://github.com/alexander-heimbuch/vuepress-theme-casper

**Comment by stefnotch** [comment]
To commit something to a different branch
https://stackoverflow.com/a/35307501

**Comment by stefnotch** [comment]
Hugo is useless for me, because to make my own theme, I'd have to learn Go templates.

**Comment by stefnotch** [comment]
Well, we quickly got Docute up and running, but [this AsciiDoctor template made by Prof. Stuetz](https://github.com/htl-leonding/asciidoctor-docker-template) is probably the way to go.

**Comment by dorfingerjonas** [comment]
we won't be using a static site generator in the future

**Comment by stefnotch** [comment]
🍿 
Was hat Prof. Stuetz sich jetzt ausgedacht? Oder habt ihr etwas cooles gefunden?
